package com.ibm.helper.jmeter.jsonhelper;

public class ConstantsHelper {	
	public static String UNIQUE_PROPERTY;
	
	public static String NAME_PROPERTY;
	public static String TYPE_PROPERTY;
	public static String ISNULL_PROPERTY;
	
	public static String ENTITY_IDENTIFIER;
	public static String NUMBER_IDENTIFIER;
	public static String ENUM_IDENTIFIER;
	public static String ENUM_ARRAY_IDENTIFIER;

	public static String MISSING_PROPERTY_ERROR_MESSAGE;
	public static String EMPTY_PROPERTY_ERROR_MESSAGE;
	public static String NOT_NUMERIC_PROPERTY_ERROR_MESSAGE;
	public static String NOT_ENUM_PROPERTY_ERROR_MESSAGE;
		
	public static String[] COMMON_PROPERTIES;
	public static String UNIQUE_RECORD_IDENTIFIER;
	public static String FOUND_ISSUES;
	public static String GENERAL_ISSUES;

	public static String UNDERSCORE_DELIMITER = "_";
	public static String ARRAY_JMETER_IDENTIFIER;
	
	public static void setUNIQUE_PROPERTY(String uNIQUE_PROPERTY) {
		UNIQUE_PROPERTY = uNIQUE_PROPERTY;
	}
	public static void setNAME_PROPERTY(String nAME_PROPERTY) {
		NAME_PROPERTY = nAME_PROPERTY;
	}
	public static void setTYPE_PROPERTY(String tYPE_PROPERTY) {
		TYPE_PROPERTY = tYPE_PROPERTY;
	}
	public static void setISNULL_PROPERTY(String iSNULL_PROPERTY) {
		ISNULL_PROPERTY = iSNULL_PROPERTY;
	}
	public static void setENTITY_IDENTIFIER(String eNTITY_IDENTIFIER) {
		ENTITY_IDENTIFIER = eNTITY_IDENTIFIER;
	}
	public static void setENUM_IDENTIFIER(String eNUM_IDENTIFIER) {
		ENUM_IDENTIFIER = eNUM_IDENTIFIER;
	}
	public static void setENUM_ARRAY_IDENTIFIER(String eNUM_ARRAY_IDENTIFIER) {
		ENUM_ARRAY_IDENTIFIER = eNUM_ARRAY_IDENTIFIER;
	}
	public static void setNUMBER_IDENTIFIER(String nUMBER_IDENTIFIER) {
		NUMBER_IDENTIFIER = nUMBER_IDENTIFIER;
	}
	public static void setMISSING_PROPERTY_ERROR_MESSAGE(String mISSING_PROPERTY_ERROR_MESSAGE) {
		MISSING_PROPERTY_ERROR_MESSAGE = mISSING_PROPERTY_ERROR_MESSAGE;
	}
	public static void setEMPTY_PROPERTY_ERROR_MESSAGE(String eMPTY_PROPERTY_ERROR_MESSAGE) {
		EMPTY_PROPERTY_ERROR_MESSAGE = eMPTY_PROPERTY_ERROR_MESSAGE;
	}
	public static void setNOT_NUMERIC_PROPERTY_ERROR_MESSAGE(String nOT_NUMERIC_PROPERTY_ERROR_MESSAGE) {
		NOT_NUMERIC_PROPERTY_ERROR_MESSAGE = nOT_NUMERIC_PROPERTY_ERROR_MESSAGE;
	}
	public static void setNOT_ENUM_PROPERTY_ERROR_MESSAGE(String nOT_ENUM_PROPERTY_ERROR_MESSAGE) {
		NOT_ENUM_PROPERTY_ERROR_MESSAGE = nOT_ENUM_PROPERTY_ERROR_MESSAGE;
	}
	public static void setCOMMON_PROPERTIES(String[] cOMMON_PROPERTIES) {
		COMMON_PROPERTIES = cOMMON_PROPERTIES;
	}
	public static void setUNIQUE_RECORD_IDENTIFIER(String uNIQUE_RECORD_IDENTIFIER) {
		UNIQUE_RECORD_IDENTIFIER = uNIQUE_RECORD_IDENTIFIER;
	}
	public static void setFOUND_ISSUES(String fOUND_ISSUES) {
		FOUND_ISSUES = fOUND_ISSUES;
	}
	public static void setGENERAL_ISSUES(String gENERAL_ISSUES) {
		GENERAL_ISSUES = gENERAL_ISSUES;
	}
	public static void setUNDERSCORE_DELIMITER(String uNDERSCORE_DELIMITER) {
		UNDERSCORE_DELIMITER = uNDERSCORE_DELIMITER;
	}
	public static void setARRAY_JMETER_IDENTIFIER(String aRRAY_JMETER_IDENTIFIER) {
		ARRAY_JMETER_IDENTIFIER = aRRAY_JMETER_IDENTIFIER;
	}	
}
